plugins:
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme

readme_index:
  enabled: false

remote_theme: pmarsceill/just-the-docs

exclude:
  - Gemfile
  - Gemfile.lock
  - build_scripts
  - "*.bat"

markdown: kramdown
kramdown:
  parse_block_html: true

baseurl: "/CaTRoX_QWR/" 
url: "https://theqwertiest.github.io"

permalink: pretty

title: CaTRoX (QWR Edition)

aux_links:
  "View on GitHub":
    - "//github.com/theqwertiest/CaTRoX_QWR"

color_scheme: "dark"

footer_content: "Copyright &copy; 2021 Yuri Shutenko.<br/>Distributed by an <a href=\"https://github.com/TheQwertiest/CaTRoX_QWR/blob/master/LICENSE\">MIT license.</a>"

ga_tracking: UA-154231909-4
